debian/tmp/usr/sbin/NetworkManager
debian/tmp/usr/bin/nm-tool
debian/tmp/usr/bin/nm-online
debian/tmp/usr/bin/nmcli
debian/tmp/usr/lib/NetworkManager/nm-dhcp-client.action
debian/tmp/usr/lib/NetworkManager/nm-dispatcher.action
debian/tmp/usr/lib/NetworkManager/nm-avahi-autoipd.action
debian/tmp/usr/lib/*/NetworkManager/libnm-settings-plugin-ifupdown.so
debian/tmp/usr/lib/*/NetworkManager/libnm-settings-plugin-ofono.so
debian/tmp/usr/lib/*/pppd/*/*.so
debian/tmp/usr/share/locale/
debian/tmp/usr/share/man/
debian/tmp/usr/share/dbus-1/system-services/
debian/tmp/usr/share/polkit-1/
debian/tmp/usr/share/bash-completion/
debian/tmp/etc/dbus-1/system.d/org.freedesktop.NetworkManager.conf
debian/tmp/etc/dbus-1/system.d/nm-dhcp-client.conf
debian/tmp/etc/dbus-1/system.d/nm-dispatcher.conf
debian/tmp/etc/dbus-1/system.d/nm-avahi-autoipd.conf
debian/tmp/etc/dbus-1/system.d/nm-ofono.conf
debian/tmp/etc/NetworkManager/dispatcher.d/
debian/tmp/lib/udev/rules.d/*.rules
debian/source_network-manager.py /usr/share/apport/package-hooks/
debian/NetworkManager.conf etc/NetworkManager/
debian/debug-helper.py usr/lib/NetworkManager/
